name: Tell a Joke

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  tell-joke:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Get joke from API
      run: |
        npm install axios
        node get-joke.js
