name: Tell a Joke

on:
  push:
    branches: [ main ]

jobs:

  tell-joke:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Get joke from API
      id: get-joke
      run: |
        npm install axios
        node get-joke.js > joke.txt
      
    - name: Create issue with joke
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: "Random Joke"
        content-filepath: ./joke.txt
