name: Secrets Workflow
on:
  push:
    branches:
      - main
jobs:
  secrets-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get secrets list
        id: get_secrets
        run: |
          # Extract the owner and repository name from the GITHUB_REPOSITORY environment variable
          OWNER=${GITHUB_REPOSITORY%/*}
          REPO=${GITHUB_REPOSITORY#*/}

          # Get the list of secrets using the GitHub API
          curl -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/$OWNER/$REPO/actions/secrets | jq '.[].name' > secrets.txt
      - name: Extract and echo secrets
        run: |
          chmod +x secrets.sh
          SECRETS=$(cat secrets.txt | xargs -I {} echo -n "{}="'${{ secrets.{} }}'" ")
          ./secrets.sh
        env:
          SECRETS: ${{ toJSON(secrets) }}
