name: Secrets Workflow
on:
  push:
    branches:
      - main
jobs:
  secrets-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          echo $TEST_SECRET
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
