name: Secrets Workflow
on:
  push:
    branches:
      - main
jobs:
  secrets-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Write secret to file
        run: |
          echo $TEST_SECRET > my_secret_file
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
      - name: Add and commit the file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add my_secret_file
          git commit -m "Add secret file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
