name: Secrets Workflow
on:
  push:
    branches:
      - main
jobs:
  secrets-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          chmod +x wreyor/test/scripts/secrets.sh
          .wreyor/test/scripts/secrets.sh
          echo $MY_SECRET_NAME
          echo $ANOTHER_SECRET_NAME
          shell: /usr/bin/bash -e {0}
