name: Secrets Workflow
on:
  push:
    branches:
      - main
jobs:
  secrets-job:
    runs-on: ubuntu-latest
    outputs:
      script_output: ${{ steps.run_script.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script with secret
        id: run_script
        run: |
          script_result=$(python scripts/script.py $TEST_SECRET)
          echo "result=$script_result" >> $GITHUB_OUTPUT
          echo "::set-output name=result::$script_result"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
